### ISSUE TITLE
[Bego Ripoll] EDA Sharks

### ISSUE THREAD

**Issue by bripollc** [Ironhack-data-bcn-april-2023/project-I-pandas#1]
This is my link:

https://github.com/bripollc/01_EDA_Sharks

:)

**Comment by ta-data-bcn** [comment]
Hola Bego!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

El repositorio está muy bien organizado, tal y como hablamos en clase, están todas las carpetas necesarias y queda súper limpio de ésta manera. Lo único que me falta ver en la organización es un file que se llame main.py o ipynb que tenga todo y éste no tiene que estar en ninguna carpeta. 
Pero aparte de esto la organización perfecta!

Readme.md ✍🏽

En general muy bien explicado!! Tiene buena estructura y se entiende lo que has hecho en tu trabajo. Te recomiendo que expandas un poco más la parte del workflow, que en cada punto expliques un poco que has hecho allí.
También añadiría son las gráficas que has sacado para enseñarlo todo ya dentro del readme.md
Y finalmente añadir también una conclusión con los datos relevantes que has encontrado. 

El código 👨🏽‍💻

Me gusta que vayas poniendo Títulos y subtítulos a lo largo de tu código, hace más fácil la compresión.  👏🏾

En general muy muy buen trabajo limpiando y usando diferentes métodos que hemos visto en clase. 
En el siguiente project tendrás que meter todos tus códigos en funciones y verás lo bien que queda!


Visualización 🎨

Las gráficas están muy muy bien has utilizado muchos métodos que hemos aprendido en clase, y se entienden todas perfectamente. Las últimas están sin título pero bueno, se entienden muy bien :))))


Muy buen primer trabajo Bego!!!! 👏🏾 🚀🚀
