### ISSUE TITLE
[Ramses Mendoza] 

### ISSUE THREAD

**Issue by RamsesMR5** [Ironhack-data-bcn-april-2023/project-I-pandas#10]
Hello!

this is my project!

https://github.com/RamsesMR5/los-peces-son-amigos-no-comida

![image](https://user-images.githubusercontent.com/129189273/233650706-214056cf-4076-4a53-b1cf-b92f40b5717c.png)

**Comment by ta-data-bcn** [comment]
Hola Jose!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

Tu repositorio está un poco desorganizado, tienen muchos files y pocas carpetas en los que organizarlos. Para el próximo proyecto te recomiendo que utilices carpetas y que metas files que no son necesarios allí. También te recomiendo que tengas un notebook que se llame main.ipynb en el que esté todo tu trabajo completo.

Readme.md ✍🏽

En general muy bien explicado!! Tiene buena estructura y se entiende lo que has hecho en tu trabajo. Lo único que añadiría son las gráficas que has sacado para enseñarlo todo ya dentro del readme.md


El código 👨🏽‍💻

Me gusta que vayas poniendo comentarios a lo largo de tu código, hace más fácil la compresión.  👏🏾
Una recomendación es que cuando vayas a subir un documento en github nunca lo subas printeando todo un dataframe, ponlo siempre con .head, .tail o .sample(). Sino hay un notebook larguísimo y se hace un poco difícil para leer. 
En general muy muy buen trabajo limpiando y usando diferentes métodos que hemos visto en clase. Para el próximo tendrás que meter tus códigos en funciones y quedará mucho más limpio.


Visualización 🎨

La visualización se me ha hecho un poco complicada, ya que solo he encontrado una gráfica, las otras veo el código pero no se si lo llegaste a printear antes de hacer el push? 
De la gráfica que sí he podido ver, está bien, ordenada y con títulos!

En general muy buen primer trabajo Jose 👏🏾 sigueeee así! me gustaron mucho tus hipótesis y cómo las has explorado. 🚀🚀🚀💪💪

**Comment by ta-data-bcn** [comment]
Hola Ramses!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

Tu repositorio está limpio y fácil de navegar! 
El .gitignore sirve para no subir cosas específicas como por ejemplo la base de datos de sharks.csv, pero al no especificar dentro del gitignore que quieres que se ignore ese documento, se ha subido igualmente.
Para el próximo proyecto recuerda que si no quieres subir algo pero lo necesitas lo especifiques en el gitignore.

Readme.md ✍🏽

No hay readme :// 
Recuerda que el readme es como un resumen de tu trabajo, en el que explicas lo que has hecho, qué métodos has utilizado, qué gráficas has hecho, y por último qué conclusiones has sacado. 
Y esto sirve que cuando la gente mire tu github pueda entender lo que has hecho y porqué.

El código 👨🏽‍💻

El código está bien Ramses!! 
Has utilizado muchos de los métodos vistos en clase y has sacado conclusiones de ellos. 
Lo único que te recomiendo es que cuando quieras visualizar las tablas utilices métodos como .value_counts, .shape, .head, .sample. Así no quedan tan grandes e igualmente puedes ver cuantas filas te han quedado. Se hace más fácil de leer también para la persona que lo está viendo. 
PD: no hace falta que pongas notebook vacíos en la carpeta de src haha, si no pones funciones mejor no lo subas! 😂


Visualización 🎨

La visualización está bien, tiene títulos (menos alguna gráfica) y labels.
Se hace un poco difícil de entender lo que quieres mostrar sin que lo tengas que explicar. En el siguiente proyecto hay mucho menos que limpiar, así que puedes explorar esto bastante más.

En general muy buen primer trabajo Ramses 👏🏾 sigueeee así!!!
