### ISSUE TITLE
Pablo_Cabadas SharksProjects

### ISSUE THREAD

**Issue by pablocabadas** [Ironhack-data-bcn-april-2023/project-I-pandas#11]
https://github.com/pablocabadas/Project_babyshark.git

![giphy-8](https://user-images.githubusercontent.com/127872717/233651236-17d44ed0-98d1-4dee-a6b3-10eed355b77e.gif)

**Comment by ta-data-bcn** [comment]
Hola Pablo!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

Tu repositorio está bastante limpio, lo único que te diría es meter imagenes o gifs o ntoebooks antiguos en carpetas. 
Por lo demás está bien!!!

Readme.md ✍🏽

El Readme esta bien! Es entretenido y sigue un hilo interesante!
Yo te recomendaría organizarlo un poco con títulos y subtítulos y por ejemplo añadir tus gráficos ahi! Y revisarlo con grammarly!!!!!!!!!!!!


El código 👨🏽‍💻

Está bastante bien tu código, ojo con los gráficos que utilizas para que cosas, por ejemplo cuando utilizas countplots o histogramas. 
Por lo demás has utilizado varias cosas vistas en clase así que bien. 
Para el próximo proyecto intenta meter tus códigos en funciones, y luego llamarlas, así quedará más limpio en general!

Visualización 🎨

La visualización está bien, acuérdate de ponerles títulos y labels para que se entiendan mejor!
En el siguiente proyecto hay mucho menos que limpiar, así que puedes explorar esto bastante más.

Buen trabajo Pablo!! 🚀
