### ISSUE TITLE
[Paula Gonzalez]

### ISSUE THREAD

**Issue by pagoba94** [Ironhack-data-bcn-april-2023/project-I-pandas#3]
The link to my repo: https://github.com/pagoba94/project1

**Comment by ta-data-bcn** [comment]
Hola PaulaGG!!! 👋🏾

Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

Me ha gustado mucho que hayas podido organizar tan bien tu trabajo!
Está súuuper bien…explicas las librerías que vas a usar, el proceso de investigación y tus resultados.
Aparte tienes bullets, títulos, subtítulos, etc. Así que súper bien hecho.
Yo te recomendaría dejar sólo la versión final de tu notebook en el repo, poniendo las otras dos versiones en una carpeta. Simplemente que no estén tan a la vista. 
También si no puedes tener 3 notebooks por ejemplo, uno para cada parte del proceso: 
-1 Exploration.ipynb
-2 Cleaning.ipynb
-3 Visualizing.ipynb
(Por ejemplo)

Readme.md ✍🏽

Para el próximo igual te diría de explicar un poco más dentro del Readme.md, añadir ahí tus gráficos, explicar un poco más todo el trabajo. El objetivo es que con el Readme se pueda entender todo lo que has hecho


El código 👨🏽‍💻

Los docstrings ayudan mucho a entender lo que estás haciendo!!  

En general muy muy buen trabajo limpiando y usando diferentes métodos. 

Has hecho perfecto la encapsulación de las funciones te felicito! 

La verdad es que para ser el primer proyecto es un proyectazo! 


Visualización 🎨

La visualización está bien, tiene títulos, labels y se entiende lo que quieres mostrar sin que lo tengas que explicar. En el siguiente proyecto hay mucho menos que limpiar, así que puedes explorar esto bastante más. Hay una librería llamada plotly que hace unas gráficas más chulas! Si te interesa puedes usarla para el siguiente trabajo! 

En general muuuuy buen primer trabajo Paula 👏🏾 sigueeee así! 🚀🚀
