### ISSUE TITLE
Jean Paul Bancelin Project 1 Sharks 

### ISSUE THREAD

**Issue by jeanpaulbr** [Ironhack-data-bcn-april-2023/project-I-pandas#4]
Hello this is my project:

https://github.com/paulbancelin/Project-1-Sharks.git

**Comment by ta-data-bcn** [comment]
Hola Paul !!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

El repo está bien organizado! Las carpetas están bien, y el gitignore funciona!                                                                                                                                                                                                                                     


Readme.md ✍🏽

El readme está un poco desorganizado, es bueno que hayas puesto títulos y subtítulos, pero la organización no está del todo acertada.
Como hemos hablado, el Readme es un resumen de tu proyecto, que empieza con una introducción, sigue con los diferentes procedimientos y acaba con una conclusión. Un poco lo que has hecho dentro de tu notebook de jupyter es lo que debería estar en el readme. 


El código 👨🏽‍💻

Me gusta que vayas poniendo comentarios a lo largo de tu código, hace más fácil la compresión.  👏🏾
Por lo demás está bien el código, podrías haber cogido más keywords relacionadas con surf ya que solo has cogido la palabra surfing, entonces puedes haber perdido datos debido a esto. 
Por lo demás el código está limpio y se entiende bien todo lo que has hecho!
Felicidades!

Visualización 🎨

Los gráficos también los has sabido hacer bien! 
Todos tienen títulos y son explicativos de lo que estás intentando evaluar, recuerda incluirlos también en el Readme la próxima vez!

Buen trabajo Paul! El próximo habrá que limpiar menos y podrás centrarte más en la parte de visualización y organización del repo	!
