### ISSUE TITLE
[Project1_Leti]

### ISSUE THREAD

**Issue by LeticiaIruela** [Ironhack-data-bcn-april-2023/project-I-pandas#5]
The link to my repo https://github.com/LeticiaIruela/Project-I-Sharks

**Comment by ta-data-bcn** [comment]
Hola Leti!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

El repositorio está un poco desorganizado, sé que has tenido bastantes issues con tu ordenador, cómo se guardaban las cosas etc. Así que no worries, pero es importante que esté un poco más organizado en el siguiente project ;) 
Con esto me refiero a que tengas un solo notebook de jupyter con todo lo que has hecho, o 3 por ejemplo organizados en cleaning, analyzing y visualizing por ejemplo. Dentro de éstos llamaras a las funciones que tienes en src y allí tendrás guardadas las funciones en .py.

También procura tener todo en sus carpetas correspondientes (imágenes en img, notebooks antiguos en old, etc…)

README ✍🏽

Sobre el Readme cuidado porque creo que hay cosas que no han salido como era tu intención, me refiero a títulos, bullet points etc, en visual tienes una opción de preview que te deja ver esto antes de pushearlo, después te lo enseño.

Pero de contenido muy bien, bien explicada la metodología, yo te recomiendo que también añadas el análisis ahi, poner las gráficas, explicar un poco más esta parte.

Por lo demás muy bien!!

El código 👨🏽‍💻

Muy bien separándolo por subtítulos, con comentarios y poniendo todo lo que ibas encontrando en los datos 👏🏾
Ojo porque en los notebooks cuando printeas, se imprime el dataset completo, lo que hace un poco difícil la lectura. Intenta (una vez ya tengas todo claro) poner .head, .tail o .sample, para que no quede impreso el dataframe entero!

En general muy muy buen trabajo limpiando y usando diferentes métodos. Muy currado!!!


Visualización 🎨

La visualización está bien, tiene títulos, labels y se entiende lo que quieres mostrar sin que lo tengas que explicar. En el siguiente proyecto hay mucho menos que limpiar, así que puedes explorar esto bastante más.
Sigue así Letiiii 🚀🚀🚀🚀🚀
