### ISSUE TITLE
Laura Moreno

### ISSUE THREAD

**Issue by laumosa** [Ironhack-data-bcn-april-2023/project-I-pandas#6]
https://github.com/laumosa/Project1-Sharks

**Comment by ta-data-bcn** [comment]
Hola Laura!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

El repo está perfecto! Todo donde tiene que estar y fácil de saber qué notebooks tienen qué códigos. 
MUY BIEN!

Readme.md ✍🏽

El Readme también la verdad que está super bien, leyendo el readme entiendo todo tu proyecto y está bien organizado con títulos y subtítulos. 
También que hayas incluido tus gráficos en el readme lo hace súper informativo así que perfecto!!!!!!!!! Felicitats 


El código 👨🏽‍💻

Empezando por tus funciones, tampoco cambiaría nada, los comentarios van explicando el funcionamiento de la función y se hace súper fácil de entender lo que cada función va a hacer!
Está súper bien!!!!!!! 


Visualización 🎨

También has hecho las funciones muy explicativas, se entiende todo lo que pretendes mostrar sin que tengas que explicarlo! Si quieres, hay otra librería llamada plotly que hace unas funciones bastante más profesionales. Igual para tu próximo proyecto te gustaría explorarla. 
A parte de esto tus gráficos tienen títulos y están limpios!!

No he visto nada que mejoraría de este trabajo, muchísimas felicidades Laura!!!!!!!

Sigue así!!!! 🚀🚀🚀🚀🚀🚀
