### ISSUE TITLE
Paula Machado

### ISSUE THREAD

**Issue by paulaRMachado** [Ironhack-data-bcn-april-2023/project-I-pandas#7]
https://github.com/paulaRMachado/Jaws-EDA.git

**Comment by ta-data-bcn** [comment]
Hello PaulaM!!! 👋🏾

Let me give you some feedback about the project.

The organization of the repository 🧹

The repository is organized cleanly, everything is in the folders as it should be and it is easy to navigate. I would only recommend to name the different notebooks by what they are, like naming the first one testing or cleaning, and the other one main (as you did).
In general, good structure of the repo! It is exactly what we were looking for!!!


Readme.md. ✍🏽

The Readme is also written nicely, you have added your graphs and explained your work there so amazing!!! It is easy to understand what your work is about and the conclusions you have made.


The code 👨🏽‍💻


Overall very very good job cleaning and using different methods. I would only say to add docstrings and comment as you go to explain a bit more clearly what you are doing. You have done a great job with the docstrings in your src file, keep it up!!!! 


visualization 🎨

The visualization is good, you have titles, labels and you understand what you want to show without having to explain it. In the next project there's a lot less to clean up, so you can explore this a lot more. You can also look into a new plotting library called plotly that makes nicer, interactive visualizations.

In general very good first project Paula  MUITO BEM!!!!!👏🏾 keep it up! I really liked your hypotheses and how you explored them 🚀🚀🚀
