### ISSUE TITLE
Jose Marin

### ISSUE THREAD

**Issue by jomape-iron** [Ironhack-data-bcn-april-2023/project-I-pandas#8]
https://github.com/jomape-iron/shark-s_project

**Comment by ta-data-bcn** [comment]
Hola Jose!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

Tu repositorio está un poco desorganizado, tienen muchos files y pocas carpetas en los que organizarlos. Para el próximo proyecto te recomiendo que utilices carpetas y que metas files que no son necesarios allí. También te recomiendo que tengas un notebook que se llame main.ipynb en el que esté todo tu trabajo completo.

Readme.md ✍🏽

En general muy bien explicado!! Tiene buena estructura y se entiende lo que has hecho en tu trabajo. Lo único que añadiría son las gráficas que has sacado para enseñarlo todo ya dentro del readme.md


El código 👨🏽‍💻

Me gusta que vayas poniendo comentarios a lo largo de tu código, hace más fácil la compresión.  👏🏾
Una recomendación es que cuando vayas a subir un documento en github nunca lo subas printeando todo un dataframe, ponlo siempre con .head, .tail o .sample(). Sino hay un notebook larguísimo y se hace un poco difícil para leer. 
En general muy muy buen trabajo limpiando y usando diferentes métodos que hemos visto en clase. Para el próximo tendrás que meter tus códigos en funciones y quedará mucho más limpio.


Visualización 🎨

La visualización se me ha hecho un poco complicada, ya que solo he encontrado una gráfica, las otras veo el código pero no se si lo llegaste a printear antes de hacer el push? 
De la gráfica que sí he podido ver, está bien, ordenada y con títulos!

En general muy buen primer trabajo Jose 👏🏾 sigueeee así! me gustaron mucho tus hipótesis y cómo las has explorado. 🚀🚀🚀💪💪
