### ISSUE TITLE
[Miguel Palos]

### ISSUE THREAD

**Issue by miguelpalospou** [Ironhack-data-bcn-april-2023/project-I-pandas#9]
https://github.com/miguelpalospou/Project-I-EDA

![image](https://user-images.githubusercontent.com/128624198/233650542-bec67491-251b-4883-9a7b-36ac1ba1496a.png)

**Comment by ta-data-bcn** [comment]
Hola Jose!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

Tu repositorio está un poco desorganizado, tienen muchos files y pocas carpetas en los que organizarlos. Para el próximo proyecto te recomiendo que utilices carpetas y que metas files que no son necesarios allí. También te recomiendo que tengas un notebook que se llame main.ipynb en el que esté todo tu trabajo completo.

Readme.md ✍🏽

En general muy bien explicado!! Tiene buena estructura y se entiende lo que has hecho en tu trabajo. Lo único que añadiría son las gráficas que has sacado para enseñarlo todo ya dentro del readme.md


El código 👨🏽‍💻

Me gusta que vayas poniendo comentarios a lo largo de tu código, hace más fácil la compresión.  👏🏾
Una recomendación es que cuando vayas a subir un documento en github nunca lo subas printeando todo un dataframe, ponlo siempre con .head, .tail o .sample(). Sino hay un notebook larguísimo y se hace un poco difícil para leer. 
En general muy muy buen trabajo limpiando y usando diferentes métodos que hemos visto en clase. Para el próximo tendrás que meter tus códigos en funciones y quedará mucho más limpio.


Visualización 🎨

La visualización se me ha hecho un poco complicada, ya que solo he encontrado una gráfica, las otras veo el código pero no se si lo llegaste a printear antes de hacer el push? 
De la gráfica que sí he podido ver, está bien, ordenada y con títulos!

En general muy buen primer trabajo Jose 👏🏾 sigueeee así! me gustaron mucho tus hipótesis y cómo las has explorado. 🚀🚀🚀💪💪

**Comment by ta-data-bcn** [comment]
Hola Miguel!!!!!! 👋🏾

Felicidades por tu primer trabajo!!
Te doy un poco de feedback del proyecto.

La organización del repositorio 🧹

Tu repo está bien organizado! No hay muchos files y están ordenados en carpetas cosa que aprecio mucho haha! Me gustaría ver un file llamado main.ipynb fuera de ninguna carpeta que es como el gran notebook en el que puedo ver todo lo que has hecho. Pero a parte de esto molt be!


Readme.md ✍🏽

Me gusta la idea de que te pones en la piel de una consultoría para hacer el trabajo, le da interés y te servirá para el futuro también. También que hayas utilizado títulos, letra en negrita etc. 
Lo único que me falta ver en el readme es un poco más de tu project, que has hecho, qué partes tiene, qué gráficas has sacado y qué conclusiones has sacado de las gráficas. 



El código 👨🏽‍💻

Muy bien separándolo por títulos y subtítulos, con comentarios y poniendo todo lo que ibas encontrando en los datos 
En general muy muy buen trabajo limpiando y usando diferentes métodos que hemos visto en clase. 
No has encapsulado tu código en funciones pero no pasa nada por ser el primer project, para el próximo sí que tendrás que hacerlo y verás que queda todo mucho más limpio!


Visualización 🎨

La visualización está bien, tiene títulos (menos alguna gráfica), labels y se entiende lo que quieres mostrar sin que lo tengas que explicar. En el siguiente proyecto hay mucho menos que limpiar, así que puedes explorar esto bastante más.
Me gusta que hayas podido explorar tantos detalles en una misma gráfica, queda muy profesional. 

Muy buen primer trabajo Miguel 👏🏾 sigueeee así!!!!!!!!!
